using System;
using System.Reflection;
using UnityEngine;
class PresenterTests {
 static int passed;
 static void Check(bool value,string message){if(!value)throw new Exception(message);}
 static void Set(object target,string name,object value)=>target.GetType().GetField(name,BindingFlags.Instance|BindingFlags.NonPublic).SetValue(target,value);
 class Fixture {
  public MonsterDashedPathPresenter Presenter=new MonsterDashedPathPresenter();public LineRenderer Line=new LineRenderer();
  public MapGeneratorBehaviour Map=new MapGeneratorBehaviour();public AStarPathfindingService Path=new AStarPathfindingService();
  public GridNodeBehaviour[] Nodes;
  public Fixture(){Line.transform.parent=Presenter.transform;Line.widthMultiplier=.12f;Line.widthCurve=new AnimationCurve();Set(Presenter,"lineRenderer",Line);Path.ActiveMap=Map;
   Nodes=new[]{Node(0,0,GridNodeType.Spawn),Node(1,0,GridNodeType.Normal),Node(1,1,GridNodeType.Target)};
  }
  GridNodeBehaviour Node(int x,int y,GridNodeType type)=>new GridNodeBehaviour{MapOwner=Map,GridPosition=new Vector2Int(x,y),WorldPosition=new Vector3(x*2,0,y*2),NodeType=type};
  public MonsterMainRouteSnapshot Route=>new MonsterMainRouteSnapshot(Map,Path,Nodes);
  public void Init(){Check(Presenter.TryInitialize(Map,out var why),why);}
  public void Show(){Init();Check(Presenter.TrySetRoute(Route,MonsterDashedPathState.Normal,out var why),why);}
 }
 static void Run(string name,Action<Fixture> test){Time.timeScale=1;test(new Fixture());passed++;Console.WriteLine("PASS "+name);}
 static void Reject(Fixture f,string field,float value){f.Show();Set(f.Presenter,field,value);Check(!f.Presenter.TrySetState(MonsterDashedPathState.Normal,out var why)&&!string.IsNullOrEmpty(why),field);Check(!f.Line.enabled&&f.Line.positionCount==0,"failure retained line");}
 static void Main(){
  Run("ordered coordinates / fixed renderer configuration",f=>{f.Show();Check(f.Line.positionCount==3&&f.Line.Positions[2].z==2&&Math.Abs(f.Line.Positions[0].y-.02f)<1e-6,"coordinates");Check(f.Line.useWorldSpace&&!f.Line.loop&&f.Line.widthMultiplier==.12f,"configuration");Check(f.Line.textureScale.x==1&&f.Line.sharedMaterial.Tiling.x==3&&f.Line.FlowOffset==0,"asset pattern authority");});
  Run("state only retains geometry / repeat / two colors",f=>{f.Show();int writes=f.Line.Writes;f.Presenter.TrySetState(MonsterDashedPathState.Blocked,out _);f.Presenter.TrySetState(MonsterDashedPathState.Blocked,out _);Check(f.Line.Writes==writes&&f.Line.colorGradient.colorKeys[0].color.g==0&&f.Line.colorGradient.alphaKeys[0].alpha==.5f,"red preview");f.Presenter.TrySetState(MonsterDashedPathState.Normal,out _);Check(f.Line.colorGradient.colorKeys[0].color.g==1&&f.Line.colorGradient.alphaKeys[0].alpha==.5f,"solid");});
  Run("identical route skips write",f=>{f.Show();f.Presenter.TrySetRoute(f.Route,MonsterDashedPathState.Normal,out _);Check(f.Line.Writes==1,"duplicate geometry");});
  Run("clear cannot resurrect / same route restores",f=>{f.Show();var route=f.Route;f.Presenter.Clear();f.Presenter.Clear();Check(!f.Presenter.TrySetState(MonsterDashedPathState.Normal,out _)&&!f.Line.enabled,"resurrected");Check(f.Presenter.TrySetRoute(route,MonsterDashedPathState.Normal,out _)&&f.Line.Writes==2,"cache survived clear");});
  Run("same snapshot moved positions / rotated normal",f=>{f.Show();var route=f.Route;foreach(var n in f.Nodes)n.WorldPosition=n.WorldPosition+new Vector3(10,0,0);f.Map.NodesRoot.rotation=Quaternion.LookRotation(new Vector3(0,1,0),new Vector3(1,0,0));Check(f.Presenter.TrySetRoute(route,MonsterDashedPathState.Blocked,out _),"refresh");Check(f.Line.Writes==2&&Math.Abs(f.Line.Positions[0].x-10.02f)<1e-5&&f.Line.transform.forward.x==1,"frame");});
  Run("rebind clears / foreign route rejected",f=>{f.Show();var other=new MapGeneratorBehaviour();Check(f.Presenter.TryInitialize(other,out _)&&!f.Line.enabled,"rebind");Check(!f.Presenter.TrySetRoute(f.Route,MonsterDashedPathState.Normal,out _),"foreign accepted");});
  Run("failed initialize revokes old binding",f=>{f.Show();Check(!f.Presenter.TryInitialize(null,out _),"init");Check(!f.Presenter.TrySetRoute(f.Route,MonsterDashedPathState.Normal,out _)&&!f.Line.enabled,"old binding");});
  Run("no topology revalidation in retained preview",f=>{f.Show();f.Map.WalkabilityRevision++;Check(f.Presenter.TrySetState(MonsterDashedPathState.Blocked,out _)&&f.Line.Writes==1,"retained");});
  Run("missing material / property",f=>{f.Line.sharedMaterial=null;Check(!f.Presenter.TryInitialize(f.Map,out _),"material");f.Line.sharedMaterial=new Material{SupportsContract=false};Check(!f.Presenter.TryInitialize(f.Map,out _),"property");});
  Run("missing / foreign renderer",f=>{Set(f.Presenter,"lineRenderer",null);Check(!f.Presenter.TryInitialize(f.Map,out _),"missing");Set(f.Presenter,"lineRenderer",f.Line);f.Line.transform.parent=null;Check(!f.Presenter.TryInitialize(f.Map,out _),"foreign");});
  Run("invalid state clears",f=>{f.Show();Check(!f.Presenter.TrySetState((MonsterDashedPathState)99,out _)&&!f.Line.enabled,"enum");});
  Run("incomplete / unordered / duplicate route",f=>{f.Init();Check(!f.Presenter.TrySetRoute(new MonsterMainRouteSnapshot(f.Map,f.Path,new[]{f.Nodes[0]}),MonsterDashedPathState.Normal,out _),"short");Check(!f.Presenter.TrySetRoute(new MonsterMainRouteSnapshot(f.Map,f.Path,new[]{f.Nodes[0],f.Nodes[2]}),MonsterDashedPathState.Normal,out _),"diagonal");Check(!f.Presenter.TrySetRoute(new MonsterMainRouteSnapshot(f.Map,f.Path,new[]{f.Nodes[0],f.Nodes[1],f.Nodes[0]}),MonsterDashedPathState.Normal,out _),"duplicate");});
  Run("missing / foreign node / wrong endpoint",f=>{f.Init();f.Nodes[1]=null;Check(!f.Presenter.TrySetRoute(f.Route,MonsterDashedPathState.Normal,out _),"null node");});
  Run("foreign node",f=>{f.Init();f.Nodes[1].MapOwner=new MapGeneratorBehaviour();Check(!f.Presenter.TrySetRoute(f.Route,MonsterDashedPathState.Normal,out _),"foreign node");});
  Run("wrong endpoint",f=>{f.Init();f.Nodes[2].NodeType=GridNodeType.Normal;Check(!f.Presenter.TrySetRoute(f.Route,MonsterDashedPathState.Normal,out _),"endpoint");});
  Run("nonfinite coordinates clear atomically",f=>{f.Show();f.Nodes[2].WorldPosition=new Vector3(float.NaN,0,0);Check(!f.Presenter.TrySetRoute(f.Route,MonsterDashedPathState.Normal,out _)&&f.Line.positionCount==0&&f.Line.Writes==1,"coordinates");});
  Run("invalid Map orientation",f=>{f.Show();f.Map.NodesRoot.rotation=new Quaternion();Check(!f.Presenter.TrySetRoute(f.Route,MonsterDashedPathState.Normal,out _)&&!f.Line.enabled,"orientation");});
  foreach(float value in new[]{-.1f,1.1f,float.NaN,float.NegativeInfinity}){var v=value;Run("state color Alpha rejects "+v,f=>{f.Show();Set(f.Presenter,"normalColor",new Color(1,1,1,v));Check(!f.Presenter.TrySetState(MonsterDashedPathState.Normal,out _)&&!f.Line.enabled,"invalid color Alpha");});}
  Run("height finite",f=>Reject(f,"surfaceHeight",float.NaN));
  Run("route replacement / recovery updates shape and color",f=>{f.Show();f.Presenter.TrySetState(MonsterDashedPathState.Blocked,out _);var middle=new GridNodeBehaviour{MapOwner=f.Map,GridPosition=new Vector2Int(0,1),WorldPosition=new Vector3(0,0,2),NodeType=GridNodeType.Normal};var replacement=new MonsterMainRouteSnapshot(f.Map,f.Path,new[]{f.Nodes[0],middle,f.Nodes[2]});Check(f.Presenter.TrySetRoute(replacement,MonsterDashedPathState.Normal,out _)&&f.Line.Writes==2&&f.Line.Positions[1].z==2&&f.Line.colorGradient.colorKeys[0].color.g==1,"replacement");});
  Run("material removed during display clears",f=>{f.Show();f.Line.sharedMaterial=null;Check(!f.Presenter.TrySetState(MonsterDashedPathState.Blocked,out _)&&!f.Line.enabled,"material loss");});
  Run("finite inputs overflow final coordinate",f=>{f.Show();Set(f.Presenter,"surfaceHeight",float.MaxValue);f.Nodes[1].WorldPosition=new Vector3(2,float.MaxValue,0);Check(!f.Presenter.TrySetRoute(f.Route,MonsterDashedPathState.Normal,out _)&&!f.Line.enabled,"position overflow");});
  Run("route copied / shared material untouched",f=>{f.Show();var material=f.Line.sharedMaterial;var before=f.Line.Positions[0];f.Nodes[0].WorldPosition=new Vector3(50,0,0);Check(f.Line.Positions[0].Equals(before)&&f.Line.sharedMaterial==material&&material.SupportsContract,"ownership");});
  Run("authored width curve and multiplier preserved",f=>{var curve=f.Line.widthCurve;f.Show();f.Presenter.TrySetState(MonsterDashedPathState.Normal,out _);Check(f.Line.widthCurve==curve&&f.Line.widthMultiplier==.12f,"width overwritten");});
  Run("flow advances / direction / state and route preserve phase",f=>{f.Show();int writes=f.Line.Writes;Check(f.Presenter.TryAdvanceFlow(.5f,out _)&&f.Line.FlowOffset==.25f,"phase");f.Presenter.TrySetState(MonsterDashedPathState.Blocked,out _);Check(f.Line.FlowOffset==.25f&&f.Line.Writes==writes,"blocked reset");foreach(var n in f.Nodes)n.WorldPosition=n.WorldPosition+new Vector3(1,0,0);f.Presenter.TrySetRoute(f.Route,MonsterDashedPathState.Normal,out _);Check(f.Line.FlowOffset==.25f,"route reset");});
  Run("pause freezes / resume continues",f=>{f.Show();f.Presenter.TryAdvanceFlow(.5f,out _);Time.timeScale=0;f.Presenter.TryAdvanceFlow(.5f,out _);Check(f.Line.FlowOffset==.25f,"pause");Time.timeScale=1;f.Presenter.TryAdvanceFlow(0f,out _);Check(f.Line.FlowOffset==.25f,"zero elapsed");f.Presenter.TryAdvanceFlow(.5f,out _);Check(f.Line.FlowOffset==.5f,"resume");});
  Run("frame subdivisions independent / wrap",f=>{f.Show();for(int i=0;i<4;i++)f.Presenter.TryAdvanceFlow(.25f,out _);Check(f.Line.FlowOffset==.5f,"frame dependence");f.Presenter.TryAdvanceFlow(2f,out _);Check(f.Line.FlowOffset==.5f,"wrap");});
  Run("flow clear / reinitialize reset / hidden does not animate",f=>{f.Show();f.Presenter.TryAdvanceFlow(.5f,out _);f.Presenter.Clear();f.Presenter.TryAdvanceFlow(.5f,out _);Check(f.Line.FlowOffset==0&&!f.Line.enabled,"hidden");f.Presenter.TrySetRoute(f.Route,MonsterDashedPathState.Normal,out _);Check(f.Line.FlowOffset==0,"clear reset");f.Presenter.TryAdvanceFlow(.5f,out _);f.Init();Check(f.Line.FlowOffset==0,"initialize reset");});
  Run("zero speed disables / speed change uses material",f=>{f.Show();f.Line.sharedMaterial.Speed=0;f.Presenter.TryAdvanceFlow(1f,out _);Check(f.Line.FlowOffset==0,"disabled");f.Line.sharedMaterial.Speed=1;f.Presenter.TryAdvanceFlow(.5f,out _);Check(f.Line.FlowOffset==.5f,"speed");});
  Run("flow leaves shared material and geometry unchanged",f=>{f.Show();var m=f.Line.sharedMaterial;f.Presenter.TryAdvanceFlow(.5f,out _);Check(f.Line.sharedMaterial==m&&m.Offset.x==.1f&&m.Tiling.x==3&&m.Speed==.5f&&f.Line.Writes==1,"shared mutation");});
  Run("missing Texture / incorrect wrapping",f=>{f.Line.sharedMaterial.Texture=null;Check(!f.Presenter.TryInitialize(f.Map,out _),"texture");f.Line.sharedMaterial.Texture=new Texture{wrapMode=TextureWrapMode.Clamp};Check(!f.Presenter.TryInitialize(f.Map,out _),"wrap");});
  foreach(float value in new[]{-1f,float.NaN,float.PositiveInfinity}){var v=value;Run("flow rejects "+v,f=>{f.Show();f.Line.sharedMaterial.Speed=v;Check(!f.Presenter.TryAdvanceFlow(.1f,out _)&&!f.Line.enabled,"speed invalid");});}
  foreach(float value in new[]{-1f,float.NaN,float.PositiveInfinity}){var v=value;Run("elapsed rejects "+v,f=>{f.Show();Check(!f.Presenter.TryAdvanceFlow(v,out _)&&!f.Line.enabled,"delta invalid");});}
  foreach(float value in new[]{0f,-1f,float.NaN,float.PositiveInfinity}){var v=value;Run("authored width rejects "+v,f=>{f.Line.widthMultiplier=v;Check(!f.Presenter.TryInitialize(f.Map,out _),"width invalid");});}
  foreach(float value in new[]{0f,-1f,float.NaN,float.PositiveInfinity}){var v=value;Run("material tiling rejects "+v,f=>{f.Line.sharedMaterial.Tiling=new Vector2(v,1);Check(!f.Presenter.TryInitialize(f.Map,out _),"tiling invalid");});}
  Run("material offset rejects NaN",f=>{f.Line.sharedMaterial.Offset=new Vector2(float.NaN,0);Check(!f.Presenter.TryInitialize(f.Map,out _),"offset invalid");});
  Run("large finite elapsed stays bounded",f=>{f.Show();f.Line.sharedMaterial.Speed=float.MaxValue;Check(f.Presenter.TryAdvanceFlow(float.MaxValue,out _)&&f.Line.FlowOffset>=0&&f.Line.FlowOffset<1,"large flow");});
  Run("independent RGBA colors survive clear and rebind",f=>{Set(f.Presenter,"normalColor",new Color(.2f,.6f,.8f,.3f));Set(f.Presenter,"blockedColor",new Color(.9f,.1f,.2f,.7f));f.Show();Check(f.Line.colorGradient.colorKeys[0].color.g==.6f&&f.Line.colorGradient.alphaKeys[0].alpha==.3f,"normal RGBA");f.Presenter.TrySetState(MonsterDashedPathState.Blocked,out _);Check(f.Line.colorGradient.colorKeys[0].color.r==.9f&&f.Line.colorGradient.alphaKeys[0].alpha==.7f,"blocked RGBA");f.Init();f.Presenter.TrySetRoute(f.Route,MonsterDashedPathState.Normal,out _);Check(f.Line.colorGradient.alphaKeys[0].alpha==.3f&&f.Line.colorGradient.colorKeys[0].color.g==.6f,"rebind colors");});
  Run("same-state color edits preserve geometry and flow / Alpha endpoints",f=>{f.Show();f.Presenter.TryAdvanceFlow(.5f,out _);int writes=f.Line.Writes;Set(f.Presenter,"normalColor",new Color(.2f,.4f,.6f,0));f.Presenter.TrySetState(MonsterDashedPathState.Normal,out _);Check(f.Line.colorGradient.alphaKeys[0].alpha==0&&f.Line.colorGradient.colorKeys[0].color.b==.6f,"normal edit");Set(f.Presenter,"blockedColor",new Color(.8f,.2f,.1f,1));f.Presenter.TrySetState(MonsterDashedPathState.Blocked,out _);Check(f.Line.colorGradient.alphaKeys[0].alpha==1,"opaque endpoint");Set(f.Presenter,"blockedColor",new Color(.9f,.3f,.2f,.8f));f.Presenter.TrySetState(MonsterDashedPathState.Blocked,out _);Check(f.Line.colorGradient.alphaKeys[0].alpha==.8f&&f.Line.colorGradient.colorKeys[0].color.g==.3f&&f.Line.Writes==writes&&f.Line.FlowOffset==.25f,"blocked edit reset geometry/flow");});
  Run("nonfinite blocked RGB rejected",f=>{f.Show();Set(f.Presenter,"blockedColor",new Color(float.NaN,0,0,.5f));Check(!f.Presenter.TrySetState(MonsterDashedPathState.Blocked,out _)&&!f.Line.enabled,"invalid RGB");});
  Console.WriteLine("PASS "+passed+" presenter contract cases (controlled Unity doubles; no native rendering).");
 }
}
